### ISSUE TITLE
Fork do Projeto

### ISSUE THREAD

**Issue by walber-silva** [tiagorlampert/alpi#2]
Olâ tiago estou criando projeto baseado no seu mais para ubuntu e derivados botei  no readme que foi baseado no seu precisando de ajuda tambem estou aqui vlw qualquer duvida  manda mensagem.

**Comment by tiagorlampert** [comment]
Legal cara. Vlw

**Comment by walber-silva** [comment]
Ainda tô construindo ele ainda mais queria fazer com python mais ainda não sei fazer.
